//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialTratamiento
    {
        public int idHistorialTratamiento { get; set; }
        public int idHistorial { get; set; }
        public int idTratamiento { get; set; }
    
        public virtual Historial Historial { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
