//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialEstudios
    {
        public int idHistorialEstudios { get; set; }
        public int idHistorial { get; set; }
        public int idEstudio { get; set; }
    
        public virtual Estudios Estudios { get; set; }
        public virtual Historial Historial { get; set; }
    }
}
