//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionHospital.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Historial()
        {
            this.HistorialEstudios = new HashSet<HistorialEstudios>();
            this.HistorialMedicamento = new HashSet<HistorialMedicamento>();
            this.HistorialTratamiento = new HashSet<HistorialTratamiento>();
        }
    
        public int idHistorial { get; set; }
        public int idPaciente { get; set; }
        public int idCita { get; set; }
        public decimal Costo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialEstudios> HistorialEstudios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialMedicamento> HistorialMedicamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialTratamiento> HistorialTratamiento { get; set; }
    }
}
